// Package builtinspec contains dependency-free language metadata for builtins.
package builtinspec

var Names = []string{
	"addToArrayStart",
	"addToArrayEnd",
	"addToDict",
	"allButFirst",
	"bhaskara",
	"capitalize",
	"date",
	"deleteFromDict",
	"dictKeys",
	"dictValues",
	"dotenvLoad",
	"dotenvGet",
	"first",
	"get",
	"getFromDict",
	"hashCode",
	"html",
	"indexOf",
	"input",
	"jsonParse",
	"jwtCreateToken",
	"jwtVerifyToken",
	"last",
	"max",
	"min",
	"mysqlConnection",
	"mysqlCreateTable",
	"mysqlDeleteFromTable",
	"mysqlDropTable",
	"mysqlGetFromTable",
	"mysqlInsertIntoTable",
	"mysqlShowTables",
	"mysqlShowTableColumns",
	"mysqlUpdateIntoTable",
	"organize",
	"randomFloat",
	"randomInteger",
	"registerRoute",
	"removeFromArray",
	"removeWhiteSpaces",
	"replace",
	"sendEmail",
	"sendWhatsapp",
	"server",
	"serveFile",
	"serveStatic",
	"show",
	"sizeOf",
	"sum",
	"toBool",
	"toFloat",
	"toInt",
	"toLowercase",
	"toString",
	"toUppercase",
	"createCsv",
	"createDoc",
	"createFile",
	"createPdf",
	"createTxt",
	"restDelete",
	"restGet",
	"restPatch",
	"restPost",
	"restPut",
	"switchCase",
	"postgresConnection",
	"postgresExec",
	"postgresQuery",
	"redisConnection",
	"redisSet",
	"redisGet",
	"redisDel",
	"supabaseConnection",
	"supabaseSelect",
	"supabaseInsert",
	"supabaseQuery",
	"supabaseUpdate",
	"supabaseDelete",
	"supabaseUpsert",
	"supabaseRpc",
	"supabaseCount",
	"supabaseSingle",
	"supabaseStorageUpload",
	"supabaseStorageDelete",
	"supabaseStoragePublicUrl",
	"supabaseStorageSignedUrl",
	"supabaseStorageDownload",
	"supabaseAuthSignUp",
	"supabaseAuthSignIn",
	"error",
	"panic",
	"u8",
	"u16",
	"u32",
	"u64",
	"i8",
	"i16",
	"i32",
	"i64",
	"wrapAdd",
	"wrapSub",
	"wrapMul",
	"checkedAdd",
	"checkedSub",
	"checkedMul",
	"satAdd",
	"satSub",
	"satMul",
	"bytes",
	"arrayOf",
	"slice",
	"fill",
	"readBytes",
	"writeBytes",
	"readU16LE",
	"readU16BE",
	"readU32LE",
	"readU32BE",
	"readU64LE",
	"readU64BE",
	"writeU16LE",
	"writeU16BE",
	"writeU32LE",
	"writeU32BE",
	"writeU64LE",
	"writeU64BE",
	"copyBytes",
	"bytesEqual",
	"sha256",
	"join", "cancel", "taskDone", "taskCancelled", "joinTimeout", "sleepMs",
	"channel", "send", "receive", "receiveOk", "receiveTimeout", "closeChannel", "channelClosed", "channelLen", "channelCap",
	"mutex", "lock", "unlock", "rwMutex", "rLock", "rUnlock",
	"waitGroup", "wgAdd", "wgDone", "wgWait", "semaphore", "acquire", "release",
	"atomicInt", "atomicLoad", "atomicStore", "atomicAdd", "atomicSwap", "atomicCompareSwap",
	"tcpListen", "tcpConnect", "tcpConnectTimeout", "tlsListen", "tlsConnect", "tlsConnectTimeout",
	"listenerAccept", "listenerAcceptTimeout", "listenerClose", "listenerClosed", "listenerAddress", "listenerPort",
	"streamRead", "streamReadExact", "streamReadTimeout", "streamWrite", "streamWriteAll", "streamClose", "streamClosed",
	"streamShutdownRead", "streamShutdownWrite", "streamLocalAddress", "streamLocalPort", "streamRemoteAddress", "streamRemotePort",
	"streamSetReadTimeout", "streamSetWriteTimeout", "tcpSetKeepAlive", "dnsLookup", "dnsLookupTimeout",
	"udpBind", "udpSendTo", "udpReceiveFrom", "udpReceiveFromTimeout", "udpClose", "udpClosed", "udpAddress", "udpPort",
	"httpApp", "httpRoute", "httpUse", "httpStatic", "httpLimitBody", "httpCompression", "httpCors",
	"httpServe", "httpServeTLS", "httpShutdown", "httpServerPort", "httpServerAddress", "httpServerRunning",
	"httpText", "httpJson", "httpHtml", "httpRedirect", "httpFile", "httpHeader", "httpCookie",
	"httpStream", "httpSSE", "sseEvent", "httpRequest", "httpStatus", "httpBody", "httpBodyBytes", "httpBodyJSON", "httpHeaders",
	"jsonStringify", "jwtSignHS256", "jwtVerifyHS256",
	"webSocketUpgrade", "webSocketConnect", "webSocketRead", "webSocketReadTimeout", "webSocketWriteText", "webSocketWriteBinary",
	"webSocketPing", "webSocketClose", "webSocketClosed",
}

func Contains(name string) bool {
	for _, item := range Names {
		if item == name {
			return true
		}
	}
	return false
}
